-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "Production"."BillOfMaterials"
(
    "BillOfMaterialsID" serial NOT NULL,
    "ProductAssemblyID" integer,
    "ComponentID" integer NOT NULL,
    "StartDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    "EndDate" timestamp without time zone,
    "UnitMeasureCode" character(3) COLLATE pg_catalog."default" NOT NULL,
    "BOMLevel" smallint NOT NULL,
    "PerAssemblyQty" numeric(8, 2) NOT NULL DEFAULT 1.00,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_BillOfMaterials_BillOfMaterialsID" PRIMARY KEY ("BillOfMaterialsID")
);

CREATE TABLE IF NOT EXISTS "Production"."Culture"
(
    "CultureID" character(6) COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_Culture_CultureID" PRIMARY KEY ("CultureID")
);

CREATE TABLE IF NOT EXISTS "Production"."Document"
(
    "DocumentNode" character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "DocumentLevel" integer,
    "Title" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Owner" integer NOT NULL,
    "FolderFlag" boolean NOT NULL DEFAULT false,
    "FileName" character varying(400) COLLATE pg_catalog."default" NOT NULL,
    "FileExtension" character varying(8) COLLATE pg_catalog."default" NOT NULL,
    "Revision" character(5) COLLATE pg_catalog."default" NOT NULL,
    "ChangeNumber" integer NOT NULL DEFAULT 0,
    "Status" smallint NOT NULL,
    "DocumentSummary" text COLLATE pg_catalog."default",
    "Document" bytea,
    rowguid uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_Document_DocumentNode" PRIMARY KEY ("DocumentNode"),
    CONSTRAINT "Document_rowguid_key" UNIQUE (rowguid)
);

CREATE TABLE IF NOT EXISTS "Production"."Illustration"
(
    "IllustrationID" serial NOT NULL,
    "Diagram" xml,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_Illustration_IllustrationID" PRIMARY KEY ("IllustrationID")
);

CREATE TABLE IF NOT EXISTS "Production"."Location"
(
    "LocationID" serial NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    "CostRate" numeric(8, 2) NOT NULL DEFAULT 0.00,
    "Availability" numeric(8, 2) NOT NULL DEFAULT 0.00,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_Location_LocationID" PRIMARY KEY ("LocationID")
);

CREATE TABLE IF NOT EXISTS "Production"."Product"
(
    "ProductID" serial NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    "ProductNumber" character varying(25) COLLATE pg_catalog."default" NOT NULL,
    "MakeFlag" smallint NOT NULL DEFAULT 1,
    "FinishedGoodsFlag" smallint NOT NULL DEFAULT 1,
    "Color" character varying(15) COLLATE pg_catalog."default",
    "SafetyStockLevel" smallint NOT NULL,
    "ReorderPoint" smallint NOT NULL,
    "StandardCost" numeric(19, 4) NOT NULL,
    "ListPrice" numeric(19, 4) NOT NULL,
    "Size" character varying(5) COLLATE pg_catalog."default",
    "SizeUnitMeasureCode" character(3) COLLATE pg_catalog."default",
    "WeightUnitMeasureCode" character(3) COLLATE pg_catalog."default",
    "Weight" numeric(8, 2),
    "DaysToManufacture" integer NOT NULL,
    "ProductLine" character(2) COLLATE pg_catalog."default",
    "Class" character(2) COLLATE pg_catalog."default",
    "Style" character(2) COLLATE pg_catalog."default",
    "ProductSubcategoryID" integer,
    "ProductModelID" integer,
    "SellStartDate" timestamp without time zone NOT NULL,
    "SellEndDate" timestamp without time zone,
    "DiscontinuedDate" timestamp without time zone,
    rowguid uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_Product_ProductID" PRIMARY KEY ("ProductID")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductCategory"
(
    "ProductCategoryID" serial NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    rowguid uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductCategory_ProductCategoryID" PRIMARY KEY ("ProductCategoryID")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductCostHistory"
(
    "ProductID" integer NOT NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone,
    "StandardCost" numeric(19, 4) NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductCostHistory_ProductID_StartDate" PRIMARY KEY ("ProductID", "StartDate")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductDescription"
(
    "ProductDescriptionID" serial NOT NULL,
    "Description" character varying(400) COLLATE pg_catalog."default" NOT NULL,
    rowguid uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductDescription_ProductDescriptionID" PRIMARY KEY ("ProductDescriptionID")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductDocument"
(
    "ProductID" integer NOT NULL,
    "DocumentNode" character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductDocument_ProductID_DocumentNode" PRIMARY KEY ("ProductID", "DocumentNode")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductInventory"
(
    "ProductID" integer NOT NULL,
    "LocationID" smallint NOT NULL,
    "Shelf" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "Bin" smallint NOT NULL,
    "Quantity" smallint NOT NULL DEFAULT 0,
    rowguid uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductInventory_ProductID_LocationID" PRIMARY KEY ("ProductID", "LocationID")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductListPriceHistory"
(
    "ProductID" integer NOT NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone,
    "ListPrice" numeric(19, 4) NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductListPriceHistory_ProductID_StartDate" PRIMARY KEY ("ProductID", "StartDate")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductModel"
(
    "ProductModelID" serial NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    "CatalogDescription" xml,
    "Instructions" xml,
    rowguid uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductModel_ProductModelID" PRIMARY KEY ("ProductModelID")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductModelIllustration"
(
    "ProductModelID" integer NOT NULL,
    "IllustrationID" integer NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductModelIllustration_ProductModelID_IllustrationID" PRIMARY KEY ("ProductModelID", "IllustrationID")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductModelProductDescriptionCulture"
(
    "ProductModelID" integer NOT NULL,
    "ProductDescriptionID" integer NOT NULL,
    "CultureID" character(6) COLLATE pg_catalog."default" NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductModelProductDescriptionCulture_ProductModelID_Product" PRIMARY KEY ("ProductModelID", "ProductDescriptionID", "CultureID")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductPhoto"
(
    "ProductPhotoID" serial NOT NULL,
    "ThumbNailPhoto" bytea,
    "ThumbnailPhotoFileName" character varying(50) COLLATE pg_catalog."default",
    "LargePhoto" bytea,
    "LargePhotoFileName" character varying(50) COLLATE pg_catalog."default",
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductPhoto_ProductPhotoID" PRIMARY KEY ("ProductPhotoID")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductProductPhoto"
(
    "ProductID" integer NOT NULL,
    "ProductPhotoID" integer NOT NULL,
    "Primary" boolean NOT NULL DEFAULT false,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductProductPhoto_ProductID_ProductPhotoID" PRIMARY KEY ("ProductID", "ProductPhotoID")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductReview"
(
    "ProductReviewID" serial NOT NULL,
    "ProductID" integer NOT NULL,
    "ReviewerName" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    "ReviewDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    "EmailAddress" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Rating" integer NOT NULL,
    "Comments" character varying(3850) COLLATE pg_catalog."default",
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductReview_ProductReviewID" PRIMARY KEY ("ProductReviewID")
);

CREATE TABLE IF NOT EXISTS "Production"."ProductSubcategory"
(
    "ProductSubcategoryID" serial NOT NULL,
    "ProductCategoryID" integer NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    rowguid uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ProductSubcategory_ProductSubcategoryID" PRIMARY KEY ("ProductSubcategoryID")
);

CREATE TABLE IF NOT EXISTS "Production"."ScrapReason"
(
    "ScrapReasonID" serial NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_ScrapReason_ScrapReasonID" PRIMARY KEY ("ScrapReasonID")
);

CREATE TABLE IF NOT EXISTS "Production"."TransactionHistory"
(
    "TransactionID" serial NOT NULL,
    "ProductID" integer NOT NULL,
    "ReferenceOrderID" integer NOT NULL,
    "ReferenceOrderLineID" integer NOT NULL DEFAULT 0,
    "TransactionDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    "TransactionType" character(1) COLLATE pg_catalog."default" NOT NULL,
    "Quantity" integer NOT NULL,
    "ActualCost" numeric(19, 4) NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_TransactionHistory_TransactionID" PRIMARY KEY ("TransactionID")
);

CREATE TABLE IF NOT EXISTS "Production"."TransactionHistoryArchive"
(
    "TransactionID" integer NOT NULL,
    "ProductID" integer NOT NULL,
    "ReferenceOrderID" integer NOT NULL,
    "ReferenceOrderLineID" integer NOT NULL DEFAULT 0,
    "TransactionDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    "TransactionType" character(1) COLLATE pg_catalog."default" NOT NULL,
    "Quantity" integer NOT NULL,
    "ActualCost" numeric(19, 4) NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_TransactionHistoryArchive_TransactionID" PRIMARY KEY ("TransactionID")
);

CREATE TABLE IF NOT EXISTS "Production"."UnitMeasure"
(
    "UnitMeasureCode" character(3) COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default" NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_UnitMeasure_UnitMeasureCode" PRIMARY KEY ("UnitMeasureCode")
);

CREATE TABLE IF NOT EXISTS "Production"."WorkOrder"
(
    "WorkOrderID" serial NOT NULL,
    "ProductID" integer NOT NULL,
    "OrderQty" integer NOT NULL,
    "StockedQty" integer,
    "ScrappedQty" smallint NOT NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone,
    "DueDate" timestamp without time zone NOT NULL,
    "ScrapReasonID" smallint,
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_WorkOrder_WorkOrderID" PRIMARY KEY ("WorkOrderID")
);

CREATE TABLE IF NOT EXISTS "Production"."WorkOrderRouting"
(
    "WorkOrderID" integer NOT NULL,
    "ProductID" integer NOT NULL,
    "OperationSequence" smallint NOT NULL,
    "LocationID" smallint NOT NULL,
    "ScheduledStartDate" timestamp without time zone NOT NULL,
    "ScheduledEndDate" timestamp without time zone NOT NULL,
    "ActualStartDate" timestamp without time zone,
    "ActualEndDate" timestamp without time zone,
    "ActualResourceHrs" numeric(9, 4),
    "PlannedCost" numeric(19, 4) NOT NULL,
    "ActualCost" numeric(19, 4),
    "ModifiedDate" timestamp without time zone NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT "PK_WorkOrderRouting_WorkOrderID_ProductID_OperationSequence" PRIMARY KEY ("WorkOrderID", "ProductID", "OperationSequence")
);

ALTER TABLE IF EXISTS "Production"."BillOfMaterials"
    ADD CONSTRAINT "FK_BillOfMaterials_Product_ComponentID" FOREIGN KEY ("ComponentID")
    REFERENCES "Production"."Product" ("ProductID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."BillOfMaterials"
    ADD CONSTRAINT "FK_BillOfMaterials_Product_ProductAssemblyID" FOREIGN KEY ("ProductAssemblyID")
    REFERENCES "Production"."Product" ("ProductID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."BillOfMaterials"
    ADD CONSTRAINT "FK_BillOfMaterials_UnitMeasure_UnitMeasureCode" FOREIGN KEY ("UnitMeasureCode")
    REFERENCES "Production"."UnitMeasure" ("UnitMeasureCode") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_BillOfMaterials_UnitMeasureCode"
    ON "Production"."BillOfMaterials"("UnitMeasureCode");


ALTER TABLE IF EXISTS "Production"."Product"
    ADD CONSTRAINT "FK_Product_ProductModel_ProductModelID" FOREIGN KEY ("ProductModelID")
    REFERENCES "Production"."ProductModel" ("ProductModelID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."Product"
    ADD CONSTRAINT "FK_Product_ProductSubcategory_ProductSubcategoryID" FOREIGN KEY ("ProductSubcategoryID")
    REFERENCES "Production"."ProductSubcategory" ("ProductSubcategoryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."Product"
    ADD CONSTRAINT "FK_Product_UnitMeasure_SizeUnitMeasureCode" FOREIGN KEY ("SizeUnitMeasureCode")
    REFERENCES "Production"."UnitMeasure" ("UnitMeasureCode") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."Product"
    ADD CONSTRAINT "FK_Product_UnitMeasure_WeightUnitMeasureCode" FOREIGN KEY ("WeightUnitMeasureCode")
    REFERENCES "Production"."UnitMeasure" ("UnitMeasureCode") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductCostHistory"
    ADD CONSTRAINT "FK_ProductCostHistory_Product_ProductID" FOREIGN KEY ("ProductID")
    REFERENCES "Production"."Product" ("ProductID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductDocument"
    ADD CONSTRAINT "FK_ProductDocument_Document_DocumentNode" FOREIGN KEY ("DocumentNode")
    REFERENCES "Production"."Document" ("DocumentNode") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductDocument"
    ADD CONSTRAINT "FK_ProductDocument_Product_ProductID" FOREIGN KEY ("ProductID")
    REFERENCES "Production"."Product" ("ProductID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductInventory"
    ADD CONSTRAINT "FK_ProductInventory_Location_LocationID" FOREIGN KEY ("LocationID")
    REFERENCES "Production"."Location" ("LocationID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductInventory"
    ADD CONSTRAINT "FK_ProductInventory_Product_ProductID" FOREIGN KEY ("ProductID")
    REFERENCES "Production"."Product" ("ProductID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductListPriceHistory"
    ADD CONSTRAINT "FK_ProductListPriceHistory_Product_ProductID" FOREIGN KEY ("ProductID")
    REFERENCES "Production"."Product" ("ProductID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductModelIllustration"
    ADD CONSTRAINT "FK_ProductModelIllustration_Illustration_IllustrationID" FOREIGN KEY ("IllustrationID")
    REFERENCES "Production"."Illustration" ("IllustrationID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductModelIllustration"
    ADD CONSTRAINT "FK_ProductModelIllustration_ProductModel_ProductModelID" FOREIGN KEY ("ProductModelID")
    REFERENCES "Production"."ProductModel" ("ProductModelID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductModelProductDescriptionCulture"
    ADD CONSTRAINT "FK_ProductModelProductDescriptionCulture_Culture_CultureID" FOREIGN KEY ("CultureID")
    REFERENCES "Production"."Culture" ("CultureID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductModelProductDescriptionCulture"
    ADD CONSTRAINT "FK_ProductModelProductDescriptionCulture_ProductDescription_Pro" FOREIGN KEY ("ProductDescriptionID")
    REFERENCES "Production"."ProductDescription" ("ProductDescriptionID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductModelProductDescriptionCulture"
    ADD CONSTRAINT "FK_ProductModelProductDescriptionCulture_ProductModel_ProductMo" FOREIGN KEY ("ProductModelID")
    REFERENCES "Production"."ProductModel" ("ProductModelID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductProductPhoto"
    ADD CONSTRAINT "FK_ProductProductPhoto_ProductPhoto_ProductPhotoID" FOREIGN KEY ("ProductPhotoID")
    REFERENCES "Production"."ProductPhoto" ("ProductPhotoID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductProductPhoto"
    ADD CONSTRAINT "FK_ProductProductPhoto_Product_ProductID" FOREIGN KEY ("ProductID")
    REFERENCES "Production"."Product" ("ProductID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductReview"
    ADD CONSTRAINT "FK_ProductReview_Product_ProductID" FOREIGN KEY ("ProductID")
    REFERENCES "Production"."Product" ("ProductID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."ProductSubcategory"
    ADD CONSTRAINT "FK_ProductSubcategory_ProductCategory_ProductCategoryID" FOREIGN KEY ("ProductCategoryID")
    REFERENCES "Production"."ProductCategory" ("ProductCategoryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."TransactionHistory"
    ADD CONSTRAINT "FK_TransactionHistory_Product_ProductID" FOREIGN KEY ("ProductID")
    REFERENCES "Production"."Product" ("ProductID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_TransactionHistory_ProductID"
    ON "Production"."TransactionHistory"("ProductID");


ALTER TABLE IF EXISTS "Production"."WorkOrder"
    ADD CONSTRAINT "FK_WorkOrder_Product_ProductID" FOREIGN KEY ("ProductID")
    REFERENCES "Production"."Product" ("ProductID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_WorkOrder_ProductID"
    ON "Production"."WorkOrder"("ProductID");


ALTER TABLE IF EXISTS "Production"."WorkOrder"
    ADD CONSTRAINT "FK_WorkOrder_ScrapReason_ScrapReasonID" FOREIGN KEY ("ScrapReasonID")
    REFERENCES "Production"."ScrapReason" ("ScrapReasonID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_WorkOrder_ScrapReasonID"
    ON "Production"."WorkOrder"("ScrapReasonID");


ALTER TABLE IF EXISTS "Production"."WorkOrderRouting"
    ADD CONSTRAINT "FK_WorkOrderRouting_Location_LocationID" FOREIGN KEY ("LocationID")
    REFERENCES "Production"."Location" ("LocationID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "Production"."WorkOrderRouting"
    ADD CONSTRAINT "FK_WorkOrderRouting_WorkOrder_WorkOrderID" FOREIGN KEY ("WorkOrderID")
    REFERENCES "Production"."WorkOrder" ("WorkOrderID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;