adventureworks:
  target: dev
  outputs:
    dev:
      type: duckdb
      
      # Dùng hàm env_var để đọc biến môi trường DUCKDB_PATH
      path: "{{ env_var('DUCKDB_PATH', 'dbt.duckdb') }}"
      
      extensions:
        - httpfs
        - aws
        - parquet
      
      external_root: "s3://lakehouse"
      
      settings:
        s3_endpoint: "adventureworksseaweedfs:8333"
        s3_use_ssl: false
        s3_url_style: "path"
        s3_access_key_id: "admin"
        s3_secret_access_key: "admin"
        s3_region: "us-east-1"