version: 2

models:
  # Staging Models
  - name: stg_adventureworks_sales
    description: "Staging table for sales orders combining header and details"
    columns:
      - name: sales_order_detail_id
        description: "Primary key for order line item"
        tests:
          - unique
          - not_null
      - name: sales_order_id
        description: "Order header identifier"
        tests:
          - not_null
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: product_id
        description: "Product identifier"
        tests:
          - not_null
      - name: order_date
        description: "Date order was placed"
        tests:
          - not_null

  - name: stg_adventureworks_customer
    description: "Staging table for customers with person and store information"
    columns:
      - name: customer_id
        description: "Primary key for customers"
        tests:
          - unique
          - not_null
      - name: is_online_customer
        description: "Flag indicating if customer is online (true) or reseller (false)"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

  - name: stg_adventureworks_product
    description: "Staging table for products with category hierarchy"
    columns:
      - name: product_id
        description: "Primary key for products"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Product name"
        tests:
          - not_null

  - name: stg_adventureworks_employee
    description: "Staging table for employees"
    columns:
      - name: employee_id
        description: "Primary key for employees"
        tests:
          - unique
          - not_null

  - name: stg_adventureworks_address
    description: "Staging table for addresses"
    columns:
      - name: address_id
        description: "Primary key for addresses"
        tests:
          - unique
          - not_null

  - name: stg_adventureworks_sales_territory
    description: "Staging table for sales territories"
    columns:
      - name: territory_id
        description: "Primary key for territories"
        tests:
          - unique
          - not_null

  - name: stg_adventureworks_ship_method
    description: "Staging table for shipping methods"
    columns:
      - name: ship_method_id
        description: "Primary key for ship methods"
        tests:
          - unique
          - not_null

  - name: stg_adventureworks_currency
    description: "Staging table for currency rates"
    columns:
      - name: currency_rate_id
        description: "Primary key for currency rates"
        tests:
          - unique
          - not_null

  - name: stg_adventureworks_vendor
    description: "Staging table for vendors"
    columns:
      - name: vendor_id
        description: "Primary key for vendors"
        tests:
          - unique
          - not_null
      - name: account_number
        description: "Vendor account number"
        tests:
          - not_null
      - name: vendor_name
        description: "Vendor name"
        tests:
          - not_null

  - name: stg_adventureworks_purchase
    description: "Staging table for purchase orders combining header and details"
    columns:
      - name: purchase_order_detail_id
        description: "Primary key for purchase order line item"
        tests:
          - unique
          - not_null
      - name: purchase_order_id
        description: "Purchase order header identifier"
        tests:
          - not_null
      - name: vendor_id
        description: "Vendor identifier"
        tests:
          - not_null
      - name: product_id
        description: "Product identifier"
        tests:
          - not_null
      - name: order_date
        description: "Date order was placed"
        tests:
          - not_null
