version: 2

sources:
  - name: adventureworks
    description: "Landing layer - Raw data from PostgreSQL stored in SeaweedFS as Parquet"
    database: ''
    schema: ''

    tables:
      # person schema
      - name: address
        external_location: "read_parquet('s3://lakehouse/landing/person/person_address.parquet')"

      - name: country
        external_location: "read_parquet('s3://lakehouse/landing/person/person_countryregion.parquet')"

      - name: person
        external_location: "read_parquet('s3://lakehouse/landing/person/person_person.parquet')"

      - name: state_province
        external_location: "read_parquet('s3://lakehouse/landing/person/person_stateprovince.parquet')"

      - name: business_entity_address
        external_location: "read_parquet('s3://lakehouse/landing/person/person_businessentityaddress.parquet')"

      # humanresources schema
      - name: employee
        external_location: "read_parquet('s3://lakehouse/landing/humanresources/humanresources_employee.parquet')"

      # production schema
      - name: product_category
        external_location: "read_parquet('s3://lakehouse/landing/production/production_productcategory.parquet')"

      - name: product_subcategory
        external_location: "read_parquet('s3://lakehouse/landing/production/production_productsubcategory.parquet')"

      - name: product
        external_location: "read_parquet('s3://lakehouse/landing/production/production_product.parquet')"

      # sales schema
      - name: currency
        external_location: "read_parquet('s3://lakehouse/landing/sales/sales_currency.parquet')"

      - name: customer
        external_location: "read_parquet('s3://lakehouse/landing/sales/sales_customer.parquet')"

      - name: sales_order_header
        external_location: "read_parquet('s3://lakehouse/landing/sales/sales_salesorderheader.parquet')"

      - name: sales_order_details
        external_location: "read_parquet('s3://lakehouse/landing/sales/sales_salesorderdetail.parquet')"

      - name: sales_territory
        external_location: "read_parquet('s3://lakehouse/landing/sales/sales_salesterritory.parquet')"

      - name: special_offer
        external_location: "read_parquet('s3://lakehouse/landing/sales/sales_specialoffer.parquet')"

      - name: store
        external_location: "read_parquet('s3://lakehouse/landing/sales/sales_store.parquet')"

      - name: currency_rate
        external_location: "read_parquet('s3://lakehouse/landing/sales/sales_currencyrate.parquet')"

      - name: country_region_currency
        external_location: "read_parquet('s3://lakehouse/landing/sales/sales_countryregioncurrency.parquet')"

      - name: sale_resaon_header
        external_location: "read_parquet('s3://lakehouse/landing/sales/sales_salesorderheadersalesreason.parquet')"

      - name: sale_resaon_details
        external_location: "read_parquet('s3://lakehouse/landing/sales/sales_salesreason.parquet')"

      # purchasing schema
      - name: ship_method
        external_location: "read_parquet('s3://lakehouse/landing/purchasing/purchasing_shipmethod.parquet')"

      - name: product_vendor
        external_location: "read_parquet('s3://lakehouse/landing/purchasing/purchasing_productvendor.parquet')"

      - name: purchase_order_details
        external_location: "read_parquet('s3://lakehouse/landing/purchasing/purchasing_purchaseorderdetail.parquet')"

      - name: purchase_order_header
        external_location: "read_parquet('s3://lakehouse/landing/purchasing/purchasing_purchaseorderheader.parquet')"
      - name: vendor
        external_location: "read_parquet('s3://lakehouse/landing/purchasing/purchasing_vendor.parquet')"

      - name: product_inventory
        external_location: "read_parquet('s3://lakehouse/landing/production/production_productinventory.parquet')"

      - name: product_location
        external_location: "read_parquet('s3://lakehouse/landing/production/production_location.parquet')"

      - name: product_transaction
        external_location: "read_parquet('s3://lakehouse/landing/production/production_transactionhistory.parquet')"

      - name: product_transaction_archive
        external_location: "read_parquet('s3://lakehouse/landing/production/production_transactionhistoryarchive.parquet')"

