version: 2

models:
  # Date Dimension
  - name: dim_date
    description: "Date dimension table with calendar attributes"
    columns:
      - name: date_key
        description: "Primary key in YYYYMMDD integer format"
        tests:
          - unique
          - not_null

  # Customer Dimensions
  - name: dim_adventureworks_internet_customer
    description: "Internet/online customer dimension"
    columns:
      - name: dim_adventureworks_internet_customer_sk
        description: "Surrogate key for internet customers"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Natural key from source system"
        tests:
          - not_null

  - name: dim_adventureworks_reseller_customer
    description: "Reseller customer dimension with store information"
    columns:
      - name: dim_adventureworks_reseller_customer_sk
        description: "Surrogate key for reseller customers"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Natural key from source system"
        tests:
          - not_null
      - name: store_id
        description: "Store natural key"
        tests:
          - not_null

  # Product Dimension
  - name: dim_adventureworks_product
    description: "Product dimension with category hierarchy"
    columns:
      - name: dim_adventureworks_product_sk
        description: "Surrogate key for products"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "Natural key from source system"
        tests:
          - not_null

  # Employee Dimension
  - name: dim_adventureworks_employee
    description: "Employee/salesperson dimension"
    columns:
      - name: dim_adventureworks_employee_sk
        description: "Surrogate key for employees"
        tests:
          - unique
          - not_null
      - name: employee_id
        description: "Natural key from source system"
        tests:
          - not_null

  # Geography Dimension
  - name: dim_adventureworks_geography
    description: "Address/location dimension with geographic hierarchy"
    columns:
      - name: dim_adventureworks_geography_sk
        description: "Surrogate key for addresses"
        tests:
          - unique
          - not_null
      - name: address_id
        description: "Natural key from source system"
        tests:
          - not_null

  # Sales Territory Dimension
  - name: dim_adventureworks_sales_territory
    description: "Sales territory dimension with metrics"
    columns:
      - name: dim_adventureworks_sales_territory_sk
        description: "Surrogate key for sales territories"
        tests:
          - unique
          - not_null
      - name: territory_id
        description: "Natural key from source system"
        tests:
          - not_null

  # Ship Method Dimension
  - name: dim_adventureworks_ship_method
    description: "Shipping method dimension"
    columns:
      - name: dim_adventureworks_ship_method_sk
        description: "Surrogate key for ship methods"
        tests:
          - unique
          - not_null
      - name: ship_method_id
        description: "Natural key from source system"
        tests:
          - not_null

  # Currency Dimension
  - name: dim_adventureworks_currency
    description: "Currency rate dimension"
    columns:
      - name: dim_adventureworks_currency_sk
        description: "Surrogate key for currency rates"
        tests:
          - unique
          - not_null
      - name: currency_rate_id
        description: "Natural key from source system"
        tests:
          - not_null

  # Fact Tables
  - name: fct_adventureworks_internet_sales
    description: "Internet sales fact table at line item grain"
    columns:
      - name: fct_adventureworks_internet_sales_pk
        description: "Primary key for fact table"
        tests:
          - unique
          - not_null
      - name: sales_order_detail_id
        description: "Natural key for order line item"
        tests:
          - not_null
      - name: order_date_key
        description: "Foreign key to dim_date"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: dim_adventureworks_internet_customer_sk
        description: "Foreign key to dim_adventureworks_internet_customer"
        tests:
          - not_null
          - relationships:
              to: ref('dim_adventureworks_internet_customer')
              field: dim_adventureworks_internet_customer_sk
      - name: dim_adventureworks_product_sk
        description: "Foreign key to dim_adventureworks_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_adventureworks_product')
              field: dim_adventureworks_product_sk
      - name: line_total
        description: "Line item total amount"
        tests:
          - not_null

  - name: fct_adventureworks_reseller_sales
    description: "Reseller sales fact table at line item grain"
    columns:
      - name: fct_adventureworks_reseller_sales_pk
        description: "Primary key for fact table"
        tests:
          - unique
          - not_null
      - name: sales_order_detail_id
        description: "Natural key for order line item"
        tests:
          - not_null
      - name: order_date_key
        description: "Foreign key to dim_date"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: dim_adventureworks_reseller_customer_sk
        description: "Foreign key to dim_adventureworks_reseller_customer"
        tests:
          - not_null
          - relationships:
              to: ref('dim_adventureworks_reseller_customer')
              field: dim_adventureworks_reseller_customer_sk
      - name: dim_adventureworks_product_sk
        description: "Foreign key to dim_adventureworks_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_adventureworks_product')
              field: dim_adventureworks_product_sk
      - name: line_total
        description: "Line item total amount"
        tests:
          - not_null
