version: 2

models:
  # Date Dimension
  - name: dim_date
    description: "Date dimension table with calendar attributes"
    columns:
      - name: date_key
        description: "Primary key in YYYYMMDD integer format"
        tests:
          - unique
          - not_null

  # Customer Dimension
  - name: dim_customer
    description: "Unified customer dimension for both internet and reseller customers"
    columns:
      - name: dim_customer_sk
        description: "Surrogate key for all customers"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Natural key from source system"
        tests:
          - not_null
      - name: customer_type
        description: "Customer type: Internet or Reseller"
        tests:
          - not_null
          - accepted_values:
              values: ['Internet', 'Reseller']

  # Product Dimension
  - name: dim_product
    description: "Product dimension with category hierarchy"
    columns:
      - name: dim_product_sk
        description: "Surrogate key for products"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "Natural key from source system"
        tests:
          - not_null

  # Employee Dimension
  - name: dim_employee
    description: "Employee/salesperson dimension"
    columns:
      - name: dim_employee_sk
        description: "Surrogate key for employees"
        tests:
          - unique
          - not_null
      - name: employee_id
        description: "Natural key from source system"
        tests:
          - not_null

  # Geography Dimension
  - name: dim_geography
    description: "Address/location dimension with geographic hierarchy"
    columns:
      - name: dim_geography_sk
        description: "Surrogate key for addresses"
        tests:
          - unique
          - not_null
      - name: address_id
        description: "Natural key from source system"
        tests:
          - not_null

  # Sales Territory Dimension
  - name: dim_sales_territory
    description: "Sales territory dimension with metrics"
    columns:
      - name: dim_sales_territory_sk
        description: "Surrogate key for sales territories"
        tests:
          - unique
          - not_null
      - name: territory_id
        description: "Natural key from source system"
        tests:
          - not_null

  # Ship Method Dimension
  - name: dim_ship_method
    description: "Shipping method dimension"
    columns:
      - name: dim_ship_method_sk
        description: "Surrogate key for ship methods"
        tests:
          - unique
          - not_null
      - name: ship_method_id
        description: "Natural key from source system"
        tests:
          - not_null

  # Workshop Dimension (Manufacturing Location)
  - name: dim_workcenter
    description: "Work center dimension representing production areas and workstations within the factory"
    columns:
      - name: dim_workcenter_sk
        description: "Surrogate key for manufacturing work centers"
        tests:
          - unique
          - not_null
      - name: location_id
        description: "Natural key from source system"
        tests:
          - unique
          - not_null
      - name: location_name
        description: "Name of the manufacturing workshop/location"
        tests:
          - not_null

  # Currency Dimension
  - name: dim_currency
    description: "Currency rate dimension"
    columns:
      - name: dim_currency_sk
        description: "Surrogate key for currency rates"
        tests:
          - unique
          - not_null
      - name: currency_rate_id
        description: "Natural key from source system"
        tests:
          - not_null

  # Vendor Dimension
  - name: dim_vendor
    description: "Vendor dimension for purchasing"
    columns:
      - name: dim_vendor_sk
        description: "Surrogate key for vendors"
        tests:
          - unique
          - not_null
      - name: vendor_id
        description: "Natural key from source system"
        tests:
          - not_null
      - name: account_number
        description: "Vendor account number"
        tests:
          - not_null

  # Fact Tables
  - name: fct_sales
    description: "Unified sales fact table at line item grain for both internet and reseller sales"
    columns:
      - name: sales_pk
        description: "Primary key for fact table"
        tests:
          - unique
          - not_null
      - name: sales_order_detail_id
        description: "Natural key for order line item"
        tests:
          - not_null
      - name: order_date_key
        description: "Foreign key to dim_date"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: dim_customer_sk
        description: "Foreign key to dim_customer"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: dim_customer_sk
      - name: dim_product_sk
        description: "Foreign key to dim_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: dim_product_sk
      - name: sales_channel
        description: "Sales channel: Internet or Reseller"
        tests:
          - not_null
          - accepted_values:
              values: ['Internet', 'Reseller']
      - name: line_total
        description: "Line item total amount"
        tests:
          - not_null

  - name: fct_purchase
    description: "Purchase order fact table at line item grain"
    columns:
      - name: purchase_pk
        description: "Primary key for fact table"
        tests:
          - unique
          - not_null
      - name: purchase_order_detail_id
        description: "Natural key for purchase order line item"
        tests:
          - not_null
      - name: order_date_key
        description: "Foreign key to dim_date"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: dim_vendor_sk
        description: "Foreign key to dim_vendor"
        tests:
          - not_null
          - relationships:
              to: ref('dim_vendor')
              field: dim_vendor_sk
      - name: dim_product_sk
        description: "Foreign key to dim_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: dim_product_sk
      - name: line_total
        description: "Line item total amount"
        tests:
          - not_null
  # Scrap Reason Dimension
  - name: dim_scrap_reason
    description: "Scrap reason dimension for manufacturing defect analysis"
    columns:
      - name: dim_scrap_reason_sk
        description: "Surrogate key for scrap reasons"
        tests:
          - unique
          - not_null
      - name: scrap_reason_id
        description: "Natural key from source system"
        tests:
          - unique
          - not_null
      - name: scrap_reason_name
        description: "Name of the scrap reason"
        tests:
          - not_null
      - name: scrap_category
        description: "Derived category grouping scrap reasons"
        tests:
          - not_null
          - accepted_values:
              values: ['Paint/Finish', 'Machining', 'Welding', 'Forming', 'Other']

  # Work Order Fact
  - name: fct_workorder
    description: "Work order fact table at work order grain for manufacturing analysis"
    columns:
      - name: workorder_pk
        description: "Primary key for fact table"
        tests:
          - unique
          - not_null
      - name: work_order_id
        description: "Natural key for work order"
        tests:
          - not_null
      - name: start_date_key
        description: "Foreign key to dim_date for start date"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: dim_product_sk
        description: "Foreign key to dim_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: dim_product_sk
      - name: order_qty
        description: "Quantity ordered for manufacturing"
        tests:
          - not_null
      - name: scrap_rate_pct
        description: "Scrap rate percentage"
        tests:
          - not_null
      - name: yield_rate_pct
        description: "Yield rate percentage"
        tests:
          - not_null
      - name: delivery_status
        description: "On Time, Late, or In Progress"
        tests:
          - not_null

  # Work Order Routing Fact
  - name: fct_workorder_routing
    description: "Work order routing fact table at operation step grain for manufacturing operations analysis"
    columns:
      - name: workorder_routing_pk
        description: "Primary key for fact table (composite surrogate)"
        tests:
          - unique
          - not_null
      - name: work_order_id
        description: "Work order identifier"
        tests:
          - not_null
      - name: operation_sequence
        description: "Operation sequence number within work order"
        tests:
          - not_null
      - name: dim_product_sk
        description: "Foreign key to dim_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: dim_product_sk
      - name: dim_workcenter_sk
        description: "Foreign key to dim_workcenter (manufacturing work center)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_workcenter')
              field: dim_workcenter_sk
      - name: planned_cost
        description: "Planned cost for this operation step"
        tests:
          - not_null
      - name: schedule_status
        description: "Schedule adherence status"
        tests:
          - not_null
          - accepted_values:
              values: ['Not Started', 'In Progress', 'On Schedule', 'Behind Schedule']